services:
  - type: web
    name: porter-backend
    runtime: docker
    rootDir: backend
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
