services:
  - type: web
    name: porter-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/porter-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080 